project:
  type: website
  output-dir: _site
  pre-render:
    - generate_title_metadata.py

website:
  title: "TDM Run Results"
  navbar:
    left:
      - href: index.qmd
        text: "Run Sets"

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full

execute:
  freeze: auto
