{
  "hash": "db7252e1aac1e45b6888f80924f1ffe4",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Household Location Burden Index\"\nsubtitle: \"Scoping document — for review, only a base scenario exists so far\"\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    embed-resources: true\nexecute:\n  echo: false\n  warning: false\n  message: false\njupyter: july2025\n---\n\n<style>\n/* tbl-colwidths alone doesn't stop a long unbroken inline-code string (a\n   file path with no spaces) from forcing its column wider than its share --\n   table-layout: auto sizes columns to fit unbreakable content regardless of\n   the colgroup hint. table-layout: fixed makes the hint authoritative, and\n   break-all on code lets long paths actually wrap instead of overflowing. */\n.fixed-table {\n  table-layout: fixed;\n  width: 100%;\n}\n.fixed-table td {\n  overflow-wrap: anywhere;\n}\n.fixed-table code {\n  white-space: normal;\n  overflow-wrap: anywhere;\n  word-break: break-all;\n}\n</style>\n\n\n\n**[← All run sets](../../index.qmd)**\n\n## The question\n\nThis study asks whether the TDM could quantify the additional **Congested\nRoadway Capacity Demand** — peak-period roadway burden — created by adding a\nfixed number of typical households (500 or 1000) at different locations\naround the region. Capturing that burden properly means letting the TDM run\nits full multimodal, all-day pipeline for those households (mode choice,\ntrip timing, route choice) and measuring the *delay it imposes on everyone\nelse already on the system*, not just the new households' own travel.\n\nThe result would be expressed as a Burden Index relative to a reference\nlocation at the region's geographic center (Murray): a household placed in\nWestern Davis County, for instance, might place meaningfully more burden on\nthe system than one placed in one of Davis County's designated City or Town\nCenters.\n\n## Decisions needed before building this\n\n| Decision | Options | Recommendation | If left unresolved |\n|---|---|---|---|\n| **N** — households per site | 500 or 1000 | 1000, for a more clearly measurable effect | Defaults to 500 (boss's first-mentioned number) |\n| **Congestion threshold** | V/C ≥ 0.8, ≥ 1.0, or report both | Report both — cheap, since both are already in the same summary CSV | Defaults to reporting both |\n| **Peak window** | AM+PM only, or all four periods | AM+PM, matching \"peak-period\" in the original ask; MD/EV available in the same file if wanted later | Defaults to AM+PM |\n| **Site list** | See \"Candidate sites\" below — Murray control (1619), Western Davis typical (684 or 602), Davis CTC (674, 610, 600, or 780) | Murray 1619 + Syracuse typical 684 + Syracuse City Center 674, for the minimal 3-scenario proof-of-methodology build | Build proceeds with the recommended picks below unless told otherwise |\n| **Network vintage(s)** | 2023 (today) only, or 2023 + 2055 (long-range Needs) | Both — burden today, plus whether the center-vs-sprawl gap holds, widens, or narrows as the region grows to its 2055 forecast. More relevant to a growth-siting decision than a single-year snapshot | Proposed as part of the initial build, not a later add-on |\n\n: {tbl-colwidths=\"[20,30,30,20]\" .fixed-table}\n\n## Proposed methodology\n\n**Design:** one **Base** run, one **Control** run (Base + N\nhouseholds added at a Murray TAZ — the geographic-center reference), and one\n**Test** run per candidate site (Base + the same N households added at that\nsite's TAZ). Same household count everywhere, so differences reflect\n*location*, not household mix.\n\n**Run this whole pattern twice — once against 2023 (today), once against\n2055 (long-range Needs)**, proposed as part of the initial build rather than\na later add-on (see \"Decisions needed\" above). The diagram below shows one\nvintage; the 2055 pass is the identical pattern against the 2055 network and\n2055 SE forecast instead.\n\n```{mermaid}\nflowchart LR\n    SE[\"Base SE data<br/>(2023 or 2055)\"] --> Base[\"Base run<br/>no HH added\"]\n    SE -->|\"+N HH at Murray\"| Control[\"Control run\"]\n    SE -->|\"+N HH at Site A\"| SiteA[\"Test: Site A\"]\n    SE -->|\"+N HH at Site B\"| SiteB[\"Test: Site B\"]\n    SE -->|\"+N HH at Site ...\"| SiteN[\"Test: Site ...\"]\n\n    Base --> Metric[\"Delta VHT = Test minus Base<br/>peak periods, congested V/C tiers\"]\n    Control --> Metric\n    SiteA --> Metric\n    SiteB --> Metric\n    SiteN --> Metric\n\n    Metric --> Index[\"Burden Index(site) =<br/>Delta VHT(site) / Delta VHT(Murray control)\"]\n```\n\n**Metric:** systemwide congested vehicle-hours-traveled (ΔVHT), not just the\nnew households' own trips — the whole point is capturing the delay imposed\non *everyone else*, which only shows up as a regionwide before/after\ndifference. Peak periods (AM, PM), filtered to links at or above a\ncongestion threshold (V/C ≥ 0.8 and/or ≥ 1.0).\n\n**Burden Index** = ΔVHT(site) ÷ ΔVHT(Murray control) — giving the\n\"1.6x\" / \"1.2x\" style figure directly, computed separately for 2023 and\n2055 so the two years can be compared side by side.\n\n::: {.callout-note}\n## A caveat on comparing 2023 and 2055 directly\nN households is a much bigger *relative* bump against a TAZ's 2023\nhousehold count than against its 2055 forecast, which already assumes\ndecades of organic growth at these sites. A rising or falling Burden Index\nbetween the two years could partly reflect that shrinking relative size,\nnot just a real shift in how the network absorbs growth at that location —\nworth calling out when the results are reported, not something the study\ndesign itself corrects for.\n:::\n\n## Baseline signal, from the registered `base` scenario\n\nThese are real numbers from an already-completed model run — not simulated\nfor illustration. That run is the region's current (2023) road network\nexactly as it exists today, with no new households added yet; reusing it\nhere meant no new traffic-model run was needed just to produce this table.\nIt shows how congested the road network already is, by time of day, using\nthe same \"how congested\" math (V/C ≥ 0.8 and ≥ 1.0 — road segments running\nat or above 80%/100% of their capacity) that will measure each candidate\nsite's impact later.\n\n::: {#baseline-table .cell execution_count=2}\n| Period | Total VHT | VHT at V/C ≥ 0.8 | VHT at V/C ≥ 1.0 |\n|---|---:|---:|---:|\n| AM | 225,355 | 66,522 (29.5%) | 17,225 (7.6%) |\n| MD | 405,888 | 43,243 (10.7%) | 908 (0.2%) |\n| PM | 338,003 | 146,780 (43.4%) | 51,135 (15.1%) |\n| EV | 312,990 | 115 (0.0%) | 0 (0.0%) |\n\nRegionwide lane-miles in this network: **9,014** (segment-direction rows).\n:::\n\n\nThis is *system scale*, not the site-comparison metric itself — it's today's\nregionwide congested-VHT backdrop that a 500–1000-household ΔVHT would be\nmeasured against. PM is the most congested period by a wide margin; AM is a\ndistant second; MD and EV carry almost no V/C≥1.0 congestion. This confirms\nAM+PM is the right peak-period scope for the Burden Index, and suggests PM\nalone may show the clearest site-to-site differences.\n\n::: {.callout-note}\n## What's still missing for Control/Test scenarios\nThis `base` scenario only has the segment summary curated so far — the\nregionwide *congestion-tier* summary (`Summary_HighwayNet.csv`, needed for\nthe Δ calculation once Control/Test scenarios exist) requires the\ncustom driver-script edit described below, then re-registering `base` with\nthat output included too. A 2055 counterpart to this `base` scenario\ndoesn't exist yet either — it needs the same one-step `import-manual-run`\nregistration against the `v10.0-beta.2` run set's already-run `Needs_2055`\nscenario, no new Cube Voyager run required (see \"How this fits\nthe run-management framework\" below). Adding Control/Test scenarios for\neither year still needs real Cube Voyager runs — see \"Decisions needed\" and\n\"Effort and runtime\" below.\n:::\n\n## Candidate sites\n\n::: {.callout-note}\nCandidates, not yet confirmed. Data-driven, but the final pick is a\ndecision for the study lead — see \"Decisions needed\" above.\n:::\n\nMethod: spatially joined the TDM's own TAZ shapefile\n(`tdm/1_Inputs/1_TAZ/WFv1000_TAZ.shp`) against WFRC's **Wasatch Choice 2050\nCenters (Vision Map)** feature service — the actual regional-centers layer\nreferenced in the original ask, queried live from\n`services1.arcgis.com/taguadKoI1XFwivx/.../Wasatch_Choice_2050_Centers_(Vision_Map)/FeatureServer`\n— then cross-referenced household counts from `SE_2023.csv`. Household/city\nfigures below are pulled live from those same local files on every render.\n\n::: {#cell-candidate-sites-map .cell execution_count=3}\n\n::: {#candidate-sites-map .cell-output .cell-output-display}\n```{=html}\n<div style=\"height:550px; width:100%;\">            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.7.0.min.js\" integrity=\"sha256-jvTGqxNp8AGWEcvNLVuKr+8j5dGe9Yw51LQkmDH+IYA=\" crossorigin=\"anonymous\"></script>                <div id=\"2ad3ddc6-a139-4f17-aad1-304ec152d404\" class=\"plotly-graph-div\" style=\"height:100%; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"2ad3ddc6-a139-4f17-aad1-304ec152d404\")) {                    Plotly.newPlot(                        \"2ad3ddc6-a139-4f17-aad1-304ec152d404\",                        [{\"colorscale\":[[0,\"#2a78d6\"],[1,\"#2a78d6\"]],\"featureidkey\":\"properties.TAZID\",\"geojson\":{\"type\":\"FeatureCollection\",\"features\":[{\"id\":\"1190\",\"type\":\"Feature\",\"properties\":{\"TAZID\":1619},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-111.891225558662,40.67975903853964],[-111.89125800774822,40.67437706303349],[-111.8922101378236,40.67443907509551],[-111.89252040831212,40.67445919839945],[-111.89328117280456,40.674456017320324],[-111.89406210986422,40.674457179305165],[-111.89638578606862,40.67444546753794],[-111.89663569584242,40.6744642466889],[-111.89663716856634,40.674485855845305],[-111.89664523256859,40.674557861863896],[-111.8966531034967,40.67461545565156],[-111.8966837908125,40.67478638034643],[-111.89669521109833,40.67484394656213],[-111.89677947463493,40.675657667669796],[-111.89699234048385,40.677679340500546],[-111.8970289823659,40.677941205356554],[-111.89705119702765,40.678097781960645],[-111.89716384162791,40.67890948007617],[-111.89727340851212,40.67940319926268],[-111.8973728109273,40.679844747587225],[-111.89712551291598,40.67984576867007],[-111.89608294666346,40.67966378452791],[-111.89609478954593,40.6797528774799],[-111.89599113966354,40.67978881537267],[-111.89592971049301,40.679796498957664],[-111.89575837765035,40.679814944717656],[-111.89552781304532,40.67982844454648],[-111.89538170253344,40.67978633665944],[-111.89521535754373,40.67973537691599],[-111.89510953593987,40.67969746055683],[-111.89507978764073,40.67968507919517],[-111.89503579295041,40.679669204843506],[-111.89499292122387,40.67964881748277],[-111.89495007361832,40.67963023163371],[-111.89490721398943,40.67961074500446],[-111.89487747781213,40.67959926435366],[-111.89481207753064,40.67957544811693],[-111.89474793274564,40.67955702725696],[-111.89469831136593,40.679562816960086],[-111.89465139355879,40.67959380969775],[-111.89461409773283,40.67963643900258],[-111.89460022468727,40.67966086965176],[-111.89460773324977,40.67969144061946],[-111.89460188958478,40.67969689104527],[-111.89460314502651,40.67970228646123],[-111.89462738679231,40.6797453397664],[-111.89466859064044,40.6798179899136],[-111.89474026559222,40.67995706733883],[-111.89474876472464,40.67997321690166],[-111.8947669943727,40.68000910991093],[-111.89480227053717,40.68008090508996],[-111.89482308345607,40.68013299349882],[-111.89486317684789,40.68021105732107],[-111.89487570749529,40.6802632099155],[-111.89487518687356,40.680312761100176],[-111.89486173542005,40.680368718514],[-111.89481615692682,40.6804114120788],[-111.89476917836011,40.68043790104613],[-111.89467517293795,40.68048727586867],[-111.89450323276121,40.680548965623174],[-111.89447848190166,40.68055636424797],[-111.89444911864862,40.68057280717452],[-111.8944175334694,40.68060007759421],[-111.89436817616867,40.68062568396971],[-111.89430926894286,40.680645058300705],[-111.89423610306994,40.68066003875944],[-111.8941425218032,40.680652655857685],[-111.89404763699638,40.6806362744023],[-111.89401443514761,40.680631126371],[-111.8939812212689,40.68062507756602],[-111.8938579397174,40.68060891584046],[-111.89378079101532,40.68059149598645],[-111.89375230997824,40.68058541047495],[-111.89365150935559,40.6805690744903],[-111.89355422229326,40.68055000865155],[-111.89336438112807,40.680511840103215],[-111.89321499739579,40.680490474525],[-111.89308214246863,40.68046627832081],[-111.89300506625433,40.680454262529985],[-111.89292917326507,40.680442237536084],[-111.89280353790801,40.68042699374468],[-111.89274650403948,40.68040941764238],[-111.89268113974937,40.68038830249528],[-111.8925872826435,40.68036020074496],[-111.89247678877818,40.68032682238445],[-111.89243522072461,40.68031543257053],[-111.89232225250394,40.68027396547214],[-111.8922259212149,40.680237774833444],[-111.89209305511893,40.68021267671636],[-111.89197096995053,40.680197404583716],[-111.89192698764431,40.68018242980909],[-111.89189251893355,40.680170984951594],[-111.89184367182263,40.68014613829604],[-111.89181149749794,40.68012927054578],[-111.89176126317324,40.68008911999487],[-111.89172178567199,40.680056994054475],[-111.89163203803102,40.679982015196344],[-111.89153497542635,40.67989087732122],[-111.89143913227518,40.6798024325188],[-111.89134758287744,40.67976980764777],[-111.891225558662,40.67975903853964]]]}}]},\"hoverinfo\":\"text\",\"hovertext\":[\"Murray (TAZ 1619) (recommended)\"],\"locations\":{\"dtype\":\"i2\",\"bdata\":\"UwY=\"},\"marker\":{\"line\":{\"color\":\"white\",\"width\":1.5}},\"name\":\"Murray control\",\"showlegend\":true,\"showscale\":false,\"z\":[1],\"type\":\"choroplethmap\"},{\"hoverinfo\":\"skip\",\"lat\":{\"dtype\":\"f8\",\"bdata\":\"uVi3bLNWREA=\"},\"lon\":{\"dtype\":\"f8\",\"bdata\":\"rGK4Ijj5W8A=\"},\"mode\":\"text\",\"showlegend\":false,\"text\":[\"Murray (TAZ 1619)\"],\"textfont\":{\"color\":\"#1B3A5C\",\"size\":11},\"type\":\"scattermap\"},{\"colorscale\":[[0,\"#eb6834\"],[1,\"#eb6834\"]],\"featureidkey\":\"properties.TAZID\",\"geojson\":{\"type\":\"FeatureCollection\",\"features\":[{\"id\":\"173\",\"type\":\"Feature\",\"properties\":{\"TAZID\":602},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-112.11267016841839,41.10373865460984],[-112.1125487035335,41.1037389268996],[-112.10304027757667,41.10371145556966],[-112.10308475910182,41.09704702098951],[-112.10308878250835,41.09642634110627],[-112.11911773410151,41.09645281070691],[-112.12233315766724,41.10158302709513],[-112.12239167995708,41.103691192335155],[-112.12189501374053,41.103687022272275],[-112.1216793783174,41.10368191573054],[-112.11267061413481,41.103694511876085],[-112.11267016841839,41.10373865460984]]]}},{\"id\":\"255\",\"type\":\"Feature\",\"properties\":{\"TAZID\":684},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-112.07077376367492,41.07469341989579],[-112.07013770590147,41.07290675598506],[-112.06803643741311,41.07009056262336],[-112.0646686258014,41.068360683232356],[-112.06469806103358,41.06022445604217],[-112.07427287134442,41.060255393695],[-112.08397823214335,41.06301821060261],[-112.08388033729845,41.07474022042525],[-112.0794199063982,41.07472984756336],[-112.07712012373176,41.07472884987819],[-112.07396417933312,41.07470966676059],[-112.07185826202559,41.07469864973663],[-112.07077376367492,41.07469341989579]]]}}]},\"hoverinfo\":\"text\",\"hovertext\":[\"West Point (TAZ 602) (alternate)\",\"Syracuse (TAZ 684) (recommended)\"],\"locations\":{\"dtype\":\"i2\",\"bdata\":\"WgKsAg==\"},\"marker\":{\"line\":{\"color\":\"white\",\"width\":1.5}},\"name\":\"Western Davis (typical)\",\"showlegend\":true,\"showscale\":false,\"z\":[1,1],\"type\":\"choroplethmap\"},{\"hoverinfo\":\"skip\",\"lat\":{\"dtype\":\"f8\",\"bdata\":\"3UzGQdOMRECP7CjEnYhEQA==\"},\"lon\":{\"dtype\":\"f8\",\"bdata\":\"6RnBcC0HXMD3pQBeyARcwA==\"},\"mode\":\"text\",\"showlegend\":false,\"text\":[\"West Point (TAZ 602)\",\"Syracuse (TAZ 684)\"],\"textfont\":{\"color\":\"#1B3A5C\",\"size\":11},\"type\":\"scattermap\"},{\"colorscale\":[[0,\"#1baf7a\"],[1,\"#1baf7a\"]],\"featureidkey\":\"properties.TAZID\",\"geojson\":{\"type\":\"FeatureCollection\",\"features\":[{\"id\":\"171\",\"type\":\"Feature\",\"properties\":{\"TAZID\":600},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-112.06452005144214,41.118083742696186],[-112.06452673924083,41.11739187869241],[-112.06454022894863,41.1159414913445],[-112.06453934235432,41.115001981344506],[-112.0645383358621,41.11346525203469],[-112.06453790476097,41.11314367584856],[-112.06455858633727,41.11176978773486],[-112.06454976320245,41.110936102593755],[-112.08377175623113,41.11094657796098],[-112.08378929835052,41.113823517503356],[-112.08377189122761,41.11501001358835],[-112.08377057033081,41.11514694514404],[-112.0837712217926,41.11612789241916],[-112.08377282204533,41.11810779935283],[-112.07996467332885,41.118103028130626],[-112.07820533620921,41.118101492658674],[-112.07727980090202,41.118100242996924],[-112.07592425638498,41.118098498995565],[-112.07560025718004,41.11809792150362],[-112.07535131768107,41.118098444020184],[-112.0751071126015,41.118097120246375],[-112.07408033077654,41.11809588895029],[-112.07068535159263,41.118081553120405],[-112.06452005144214,41.118083742696186]]]}},{\"id\":\"181\",\"type\":\"Feature\",\"properties\":{\"TAZID\":610},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-112.05484433128488,41.14715721797485],[-112.05484408703002,41.146993278241304],[-112.05484725174519,41.144960188294014],[-112.05484987828302,41.14348828892089],[-112.05485025902772,41.14209928158538],[-112.054852893986,41.13988423702713],[-112.05486110361427,41.13987605481438],[-112.05856436631538,41.139874509392634],[-112.05957597379867,41.1398742160592],[-112.06000134635245,41.139873905475504],[-112.06091761597533,41.13987267610189],[-112.06251189796025,41.139873294268064],[-112.06337695334953,41.13987341851109],[-112.06446957206941,41.13987233427902],[-112.06449297079982,41.143382459653196],[-112.06449400790545,41.14352026944296],[-112.06449391778096,41.14380942071749],[-112.0644955801581,41.14575418942339],[-112.06447788601926,41.14583902625517],[-112.06448731976722,41.14664333543472],[-112.06449434421779,41.147151310268384],[-112.0642452796883,41.147150909472245],[-112.06367566135538,41.147150766469494],[-112.06313228479229,41.147152179999814],[-112.05484433128488,41.14715721797485]]]}},{\"id\":\"245\",\"type\":\"Feature\",\"properties\":{\"TAZID\":674},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-112.06459264914197,41.09692001336959],[-112.06459254826225,41.096397557662826],[-112.06459062821287,41.09458248862146],[-112.06459077495408,41.094075343812094],[-112.064590673163,41.09406903923876],[-112.06459025848943,41.09374836264036],[-112.06459062162403,41.093180862975636],[-112.06458960188972,41.09304395264578],[-112.06458921456837,41.0926512127065],[-112.06458988876909,41.09232422045428],[-112.06458832193995,41.091784662916595],[-112.06460893102275,41.08915236922794],[-112.06799896813037,41.08917414076879],[-112.06878367089031,41.089179475118556],[-112.07175576234452,41.089198706911446],[-112.07419440644115,41.08921472977775],[-112.07423132463342,41.08921528635101],[-112.07677893007104,41.089196008557515],[-112.07978789411224,41.08921288688884],[-112.08003080162709,41.08921421322613],[-112.08031180302264,41.089215181863835],[-112.0805880426768,41.08921619447673],[-112.08059417193694,41.08922694644324],[-112.08184588372602,41.09149959694557],[-112.08195388172724,41.09169585521844],[-112.08231833360887,41.09235541150837],[-112.08246054057963,41.09260449434226],[-112.08260390956609,41.092851764493496],[-112.08275085115295,41.0930990008775],[-112.08290135058861,41.09334530283205],[-112.08305302688264,41.093590692726124],[-112.08320707055758,41.09383515936187],[-112.0833646573553,41.09407779088698],[-112.08352462637697,41.09432039977882],[-112.08368696284585,41.09456208537956],[-112.08385166678072,41.09480284767905],[-112.08381232753877,41.096103953771056],[-112.083809835551,41.096531850839234],[-112.08157422874827,41.09649701152326],[-112.0802306716068,41.09632765801346],[-112.07411699576235,41.09630374843835],[-112.07410141172937,41.09695516267948],[-112.06459264914197,41.09692001336959]]]}},{\"id\":\"351\",\"type\":\"Feature\",\"properties\":{\"TAZID\":780},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-111.90066988898943,40.98668122402095],[-111.90066946916137,40.98668086067147],[-111.90064258354639,40.986657607331324],[-111.90062147203665,40.9866393480046],[-111.90039541778067,40.986433387086535],[-111.90025661631192,40.98630052158854],[-111.90017620640097,40.986223498793684],[-111.90012786973891,40.98617489108333],[-111.89996335629331,40.986009236519536],[-111.8997577080558,40.985791224305],[-111.89955926165355,40.98556946218853],[-111.89936801949688,40.98534413035034],[-111.89929104940839,40.985248363041784],[-111.89922376272976,40.98516464324999],[-111.89918999300995,40.985128964335104],[-111.89863393998407,40.984335073281954],[-111.89852701787494,40.98418251761542],[-111.89852677286383,40.98418207002067],[-111.89840880121332,40.983968145257734],[-111.89830171053441,40.98378521444437],[-111.89826071459042,40.98370783807782],[-111.89822815571016,40.983647062754564],[-111.89798790015759,40.98319033180385],[-111.89789478125994,40.98296810646806],[-111.89768257094663,40.98241319857604],[-111.8972198018682,40.981203088134315],[-111.89697498113219,40.980562542899634],[-111.89732488841784,40.98056341485149],[-111.8977040827081,40.98056406578237],[-111.8977039471318,40.98056371011688],[-111.89789474465046,40.980564022161694],[-111.89809372883536,40.980564093551386],[-111.89869176082591,40.98056501789294],[-111.89976276547915,40.98056603183301],[-111.90145975092898,40.98056907860508],[-111.90192478865633,40.980580034218384],[-111.90231581556637,40.98062904103356],[-111.90239477261149,40.98066607688028],[-111.90268777270558,40.98080503004779],[-111.90299677283625,40.981045018208064],[-111.9032387144031,40.98124004002411],[-111.90341672307132,40.981384035996456],[-111.90378274551522,40.981682037740185],[-111.90417480144454,40.98194506280692],[-111.90446477272565,40.98205304726779],[-111.90460978262271,40.98208704103317],[-111.90471178137079,40.98210506751108],[-111.90492378931945,40.982127094745984],[-111.90508974438343,40.982128043889595],[-111.90636473130166,40.98213604244156],[-111.90648278333926,40.98213709596846],[-111.90888678506026,40.98215302809743],[-111.91133942053199,40.98217005698018],[-111.91185378333859,40.98217103393951],[-111.91431377021634,40.982178032455906],[-111.91527191873426,40.98223384590048],[-111.91527036087187,40.9822340555472],[-111.91526479978005,40.982234803234356],[-111.91514615466227,40.98225105897156],[-111.91495643189758,40.9822849941602],[-111.91476918564224,40.98232611586762],[-111.91474461080767,40.98233242107622],[-111.9145844033966,40.98237352339461],[-111.91440327368537,40.982427207325244],[-111.91422579646655,40.98248716767699],[-111.91405197170018,40.982553404466955],[-111.91390785811502,40.9826152382977],[-111.91388275269557,40.982626090315954],[-111.9137177666844,40.98270405714535],[-111.91355773673381,40.98278801989116],[-111.9134712923143,40.98283856118429],[-111.9134038563712,40.982878329440766],[-111.91332153308143,40.982930515275605],[-111.91325479204387,40.982973104681875],[-111.91317689804531,40.98302807575956],[-111.9131117596596,40.983074317784244],[-111.9130656164502,40.98310941402605],[-111.9129747194541,40.98317908649198],[-111.91288920370047,40.98325195648529],[-111.91284607096658,40.98328901328312],[-111.91262012018925,40.98348918599094],[-111.9123757372129,40.983706028604985],[-111.911765779753,40.984248097922666],[-111.91149466293244,40.984488631523746],[-111.9113839873082,40.98458693913425],[-111.91133259959022,40.98462996453719],[-111.91124073351882,40.98470706866716],[-111.91071110532201,40.9851877827259],[-111.91069226806687,40.98520970773008],[-111.91063505797175,40.98527657281578],[-111.91059639656388,40.98531410600407],[-111.9105611534924,40.98534832061738],[-111.91051928121058,40.98538836267601],[-111.9105013141402,40.98540554431576],[-111.91036156470689,40.98553005903766],[-111.91030833601631,40.98557494427934],[-111.91017836793463,40.985685003705036],[-111.90916750210587,40.98654409411608],[-111.90881167011213,40.986846661666185],[-111.90788333334437,40.98763407830523],[-111.90756416289089,40.98790438528818],[-111.90680218591127,40.988549703798],[-111.90576707209624,40.989443337943875],[-111.90555323037707,40.989627882400164],[-111.90541638293499,40.98974234047362],[-111.90537927121228,40.98977319823864],[-111.9052315194575,40.98972931455355],[-111.90503787480802,40.989671565424274],[-111.9046991161298,40.98953783035835],[-111.90425304912898,40.98936136035833],[-111.90350086801675,40.98893144937522],[-111.90338748694761,40.9888665761844],[-111.9033118685981,40.98879070804635],[-111.90331167213719,40.98879051140772],[-111.90324268929604,40.98872139143777],[-111.9030343277442,40.98851217226142],[-111.90283655446308,40.98828887928978],[-111.90278050722945,40.988232685232404],[-111.90277604849408,40.98822818817726],[-111.90275848865747,40.988213024542],[-111.90271048414314,40.98817141012769],[-111.90263949743778,40.98811800749666],[-111.90256380895559,40.98806851511815],[-111.90233252758509,40.98792466481273],[-111.90227007481658,40.98788409294525],[-111.90210535232501,40.98777672825826],[-111.90197785656207,40.9876907518436],[-111.90188218150642,40.9876259674082],[-111.90184834194555,40.987602811100096],[-111.90159072739506,40.987419349498786],[-111.90139050898335,40.98726966839306],[-111.90133947294595,40.987231423612],[-111.90130221966714,40.987201988162596],[-111.90123354929737,40.987148380072334],[-111.90109314852705,40.98703877441679],[-111.90087165077371,40.98685537565928],[-111.90085424542201,40.98684102215094],[-111.90066988898943,40.98668122402095]]]}}]},\"hoverinfo\":\"text\",\"hovertext\":[\"West Point (TAZ 600) (alternate)\",\"Clinton (TAZ 610) (alternate)\",\"Syracuse (TAZ 674) (recommended)\",\"Farmington (TAZ 780) (alternate)\"],\"locations\":{\"dtype\":\"i2\",\"bdata\":\"WAJiAqICDAM=\"},\"marker\":{\"line\":{\"color\":\"white\",\"width\":1.5}},\"name\":\"Davis City\\u002fTown Center\",\"showlegend\":true,\"showscale\":false,\"z\":[1,1,1,1],\"type\":\"choroplethmap\"},{\"hoverinfo\":\"skip\",\"lat\":{\"dtype\":\"f8\",\"bdata\":\"6xUxiKiOREDLiP25XpJEQNA0VU3pi0RAMmBYXQJ+REA=\"},\"lon\":{\"dtype\":\"f8\",\"bdata\":\"0ADVFb8EXMD7mRmX0QNcwPWhxwWzBFzATsXYxuX5W8A=\"},\"mode\":\"text\",\"showlegend\":false,\"text\":[\"West Point (TAZ 600)\",\"Clinton (TAZ 610)\",\"Syracuse (TAZ 674)\",\"Farmington (TAZ 780)\"],\"textfont\":{\"color\":\"#1B3A5C\",\"size\":11},\"type\":\"scattermap\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"map\":{\"center\":{\"lat\":41.025771541439326,\"lon\":-112.02754793969955},\"style\":\"carto-positron\",\"zoom\":8.6},\"margin\":{\"l\":0,\"r\":0,\"t\":10,\"b\":0},\"legend\":{\"orientation\":\"h\",\"yanchor\":\"bottom\",\"y\":1.0,\"xanchor\":\"left\",\"x\":0},\"height\":550},                        {\"displayModeBar\": false, \"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('2ad3ddc6-a139-4f17-aad1-304ec152d404');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n:::\n:::\n\n\n::: {#candidate-sites-table .cell execution_count=4}\n| Candidate | TAZID | City | HH | Pop | Note |\n|---|---:|---|---:|---:|---|\n| Murray control | 1619 | Murray | 1,440 | 2,663 | Populous, ordinary residential TAZ -- geographic-center reference |\n| Western Davis -- typical (recommended) | 684 | Syracuse | 751 | 2,511 | Large low-density subdivision, no designated center nearby |\n| Western Davis -- typical (alternate) | 602 | West Point | 404 | 1,747 | Further west by X-coordinate; smaller sample |\n| Davis CTC -- Syracuse City Center (recommended) | 674 | Syracuse | 398 | 1,367 | Same city as the recommended typical site -- isolates center-vs-not |\n| Davis CTC -- Clinton Town Center (alternate) | 610 | Clinton | 185 | 626 |  |\n| Davis CTC -- West Point City Center (alternate) | 600 | West Point | 346 | 1,051 |  |\n| Davis CTC -- Station Park, Farmington (alternate, Urban Center) | 780 | Farmington | 301 | 1,130 | Larger/more significant center, for a bigger contrast |\n:::\n\n\n**Recommendation:** pair the Syracuse typical site (684) against the Syracuse\nCity Center (674) — same city, so the comparison isolates \"designated center\nvs. not\" rather than mixing in city-level differences, which is exactly the\ncontrast the original ask describes. Combined with the Murray control\n(1619), that's the minimal 3-scenario build (plus `base`) needed to prove the\nmethodology end-to-end before expanding to a fuller site list.\n\n## What the model already gives us to work with\n\nThis isn't hypothetical — the pieces exist in the TDM today, just not wired\ntogether for this purpose:\n\n| Need | Existing TDM piece | Status |\n|---|---|---|\n| Systemwide VMT/VHT by period, purpose, and congestion tier (V/C ≥ 0.8, ≥ 1.0) | `2_ModelScripts/7_PostProcessing/4_BCA_Summaries/02_Summarize_HighwayNet.s` | Exists, does exactly this — but its `READ FILE` line is **commented out** in the default driver script, so it doesn't currently run |\n| A way to add households to a specific TAZ without touching anything else | `WFRC_SEFile` / `MAG_SEFile` — plain TAZ-level `TOTHH`/`HHPOP` CSVs | Exists; this framework already has a proven pattern for generating per-scenario SE variants (used for the `non-motorized-2023` study) |\n| 2023 and 2055 base networks to build on | The `v10.0-beta.2` run set's `Base_2023` and `Needs_2055` scenarios, both already run in this repo | 2023 **done** — registered as this run set's own `base` scenario via `import-manual-run`. 2055 not yet registered, but the same one-step `import-manual-run` against the already-run `Needs_2055` scenario is all it needs |\n| Household composition (size, income, workers, autos) for the \"typical household\" | `1_HHDisag_AutoOwn/` (LifeCycle → HHDisaggregation → AutoOwnership) | The model derives this itself from `TOTHH`/`HHPOP`, using distributions that already respond to local accessibility — there's no separate lever to force a specific household profile |\n\n: {tbl-colwidths=\"[35,30,35]\" .fixed-table}\n\n## How this fits the run-management framework\n\nMechanically, this is a new run set — `household-location-burden` —\nfollowing the same pattern already proven by `non-motorized-2023` and\n`bring-work-trips-closer-to-home`:\n\n- **`base`** (2023) — **done**. Registered by reusing the existing\n  `v10.0-beta.2-2023` run rather than re-running full feedback from scratch.\n  To pick up the BCA congestion-tier summary once the driver script is\n  edited, its raw folder can be re-entered via `start_at_label` (resuming\n  just the post-processing steps) rather than a full re-run.\n- **`base-2055`** — same treatment, reusing `v10.0-beta.2`'s already-run\n  `Needs_2055` scenario. Not yet registered.\n- **`control-murray-2023`** / **`control-murray-2055`** and one\n  **`site-<name>-2023`** / **`site-<name>-2055`** pair per candidate\n  location — each pointed at its own generated SE file (drawn from the\n  matching year's SE forecast) via `overrides.WFRC_SEFile`, the same\n  relative-path mechanism `non-motorized-2023` uses.\n- A shared **custom driver script** (this run set's own copy of\n  `__HailMary_1Subfolder.s`, with the BCA summary line turned on) — the\n  framework's existing `driver_script` mechanism, no core code changes\n  needed.\n- **Outputs curated**: just the small `Summary_HighwayNet.csv` per\n  scenario — well under the size ceiling, no raw network/matrix files\n  committed.\n- A small Burden Index calculation module, reported here once real runs\n  exist — same shape as `non-motorized-2023`'s `report_loader.py`.\n\nNo changes to the TDM codebase, the orchestrator's core logic, or how Cube\nVoyager runs are required — this is entirely new configuration plus one\ncustom driver script, the same category of work as every other run set in\nthis repo.\n\n## Effort and runtime\n\nEach Test/Control scenario needs a **full feedback run** (mode choice\nlogsums + four-period assignment) — households are added before\ndisaggregation, so nothing upstream can be skipped or reused between sites.\nOnly the two Base runs benefit from reuse (both already run, neither needs\nre-running). Running both the 2023 and 2055 vintages roughly doubles\nthe Test/Control run count for the same site list: N sites × 2 years + 2\ncontrol runs, against two free Base runs. Runtime scales linearly with\nnumber of sites *and* years; `max_parallel_runs` (already supported, not yet\nexercised on a real multi-scenario batch) could help once Cube Voyager\nlicensing/hardware limits on this workstation are confirmed.\n\n**Why not combine multiple sites into one run?** Congestion is non-linear —\nthat's the whole reason V/C-tiered VHT is the metric. Adding households from\ntwo sites in the same run gives you their *combined* effect on network\ndelay, with no way to split credit between them afterward (their trips might\nstack on the same congested links, or might not interact at all). Base and\nControl aren't combinable either — they're mutually exclusive states of the\nsame synthetic population. Recovering true per-site effects from combined\nruns would need a full factorial design (every combination, solved for\ninteraction terms), which needs *more* runs than one-at-a-time, not fewer.\nSo N candidate sites need N separate Test runs against one shared Base — this\ndesign is already the minimal N+1, and the +1 is free (Base is reused, not\nre-run).\n\nSuggested build order:\n1. Confirm the Base-run reuse strategy and the driver-script edit; validate\n   `Summary_HighwayNet.csv` comes out as expected on the existing 2023 Base\n   run alone.\n2. Register `base-2055` the same way, and confirm it too.\n3. Build SE generation + one real site + the Murray control for **2023\n   only**; validate the ΔVHT / Burden Index math end-to-end on real output\n   before committing to the full site list or the second year.\n4. Once proven, replicate that same site + control for **2055**, to confirm\n   the pattern holds across both vintages.\n5. Add the remaining sites from the confirmed list, for both years.\n\n## Bottom line\n\nThe metric, the SE-modification mechanism, and the run-set framework are all\nalready proven in this repo for other studies — this is a matter of\nconfiguration and one small driver-script change, not new engineering. Every\nremaining decision above (N, congestion threshold, peak window, final site\npicks, network vintages) has a sensible default, so the build can proceed on\nthe recommended picks — 2023 and 2055, both — unless told otherwise.\n\n",
    "supporting": [
      "scoping_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n<script>\nwindow.PlotlyConfig = {MathJaxConfig: 'local'};\nif (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n</script>\n<script type=\"module\">import \"https://cdn.plot.ly/plotly-3.7.0.min\"</script>\n\n"
      ]
    }
  }
}